version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: harm_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: harm_user
      MYSQL_PASSWORD: harm_password
      MYSQL_DATABASE: harm_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: